### ISSUE TITLE
KeyError when browsing continents

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-dirble#11]
Running Mopidy develop and Mopidy-Dirble develop (equivalent with 1.1.2).
1. ncmpcpp
2. Browse
3. Dirble
4. Select any continent: Europe, North America, etc

``` python
ERROR    2015-12-04 11:00:36,136 [9506:Core-25] mopidy.core.library
  DirbleBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/jodal/mopidy-dev/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/home/jodal/mopidy-dev/mopidy/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/home/jodal/dev/virtualenvs/mopidy2/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/home/jodal/dev/virtualenvs/mopidy2/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/home/jodal/dev/virtualenvs/mopidy2/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/home/jodal/dev/virtualenvs/mopidy2/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/jodal/mopidy-dev/mopidy-dirble/mopidy_dirble/actor.py", line 48, in browse
    for country in self.backend.dirble.countries(identifier):
  File "/home/jodal/mopidy-dev/mopidy-dirble/mopidy_dirble/client.py", line 102, in countries
    if continent is None or c['continent_id'] == continent:
KeyError: u'continent_id'
```

**Comment by adamcik** [comment]
Fixed in https://github.com/mopidy/mopidy-dirble/commit/d9c3db2de92f03d0e1eaa1328de7d7a21bb1e7dd
