### ISSUE TITLE
Error trying to browse Dirble

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-dirble#12]
I get an empty list when I try to browse the Dirble 1.2.0 directory in Mopidy.

Log contains:

```
ERROR    DirbleBackend backend caused an exception.
Traceback (most recent call last):
  File "/Users/jcass/PycharmProjects/Mopidy/mopidy/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/Users/jcass/PycharmProjects/Mopidy/mopidy/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/mopidy_dirble/actor.py", line 39, in browse
    result.append(translator.country_to_ref(country))
  File "/usr/local/lib/python2.7/site-packages/mopidy_dirble/translator.py", line 44, in country_to_ref
    uri = unparse_uri('country', country['country_code'].lower())
TypeError: string indices must be integers
```

Tacking a quick look at the code, I can't see how https://github.com/mopidy/mopidy-dirble/blob/0516e2743e841ce1e5891048d86419c7e1bc6658/mopidy_dirble/translator.py#L44 could work since `country` only refers to the two-letter country code that is read from the config file.

Perhaps something went wrong when this was merged?

**Comment by adamcik** [comment]
Might be an other breaking API change from Dirbles side, their API stability hasn't been great :( Need to double check as it could of course be my fault.

**Comment by adamcik** [comment]
Trick to reproducing is to have `dirble/countries` set. Looks like something I broke when fixing #11. I'll to see about how to fix this.
